title: Regatta Docs
description: Documentation for the distributed key-value store Regatta
remote_theme: just-the-docs/just-the-docs@v0.7.0

permalink: pretty

logo: "/static/regatta.png"
favicon_ico: "/static/regatta-favicon.svg"

aux_links:
  GitHub: https://github.com/jamf/regatta

plugins:
- jekyll-remote-theme
- jekyll-relative-links

nav_external_links:
- title: Regatta on GitHub
  url: https://github.com/jamf/regatta
- title: Regatta Helm Chart
  url: https://github.com/jamf/regatta-helm

exclude:
- api.tmpl

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/jamf/regatta"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "tree"
